mqtt.broker=tcp://localhost:1883
mqtt.clientId=assignment03-cus
mqtt.username=
mqtt.password=
mqtt.topic.tms=assignment03/tms/telemetry

serial.port=COM3
serial.baudRate=9600

http.port=8080
dbs.pushUrl=

level.l1=50
level.l2=80
level.t1.ms=5000
tms.timeout.ms=3000

task.cus.period.ms=500
task.mqtt.period.ms=500
task.serial.period.ms=500
task.valve.period.ms=500
task.http.period.ms=500

